# Generated by Django 2.2.1 on 2019-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='you nickname', max_length=63),
            preserve_default=False,
        ),
    ]
