# Generated by Django 2.2.1 on 2019-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190513_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
