# Generated by Django 2.2.1 on 2019-05-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
    ]
